<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\2. LogicLayer\2. LogicLayer.csproj" />
    <ProjectReference Include="..\3. CoreLayer\3. CoreLayer.csproj" />
    <ProjectReference Include="..\4. DataLayer\4. DataLayer.csproj" />
  </ItemGroup>

</Project>
